server:
  port: 8761

spring:
  application:
    name: EurekaServer

eureka:
  client:
    # Un servidor Eureka NO debe registrarse a sí mismo
    register-with-eureka: false
    fetch-registry: false
  server:
    # Intervalo de expulsión de instancias caídas (puedes dejarlo por defecto)
    eviction-interval-timer-in-ms: 60000

management:
  endpoints:
    web:
      exposure:
        include: health,info
